spring:
  application:
    name: chat-reactivo-basico
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactivo
    username: postgres
    password: 1234

server:
  port: 8080

logging:
  level:
    org.springframework.r2dbc: INFO
